### ISSUE TITLE
tips: 增加一些细节

### ISSUE THREAD

**Issue by lianghx-319** [deepexi/devops-fe-hire#1]
**Demo**
- 有能力的可以部署一个线上的 demo 并附上链接

**Code Review**
- 尽量保存自己的代码，可以将代码保存到 github 私有仓库
- 面试会有 review 的环节

**重申说明**
- 面试题目并没有「套代码」的意思
- 所有实现都已经在线上了，本面试题仅提供一个贴近工作内容的筛选方式

**Comment by snowlocked** [comment]
已采纳建议，谢谢补充
